name: Test Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Get Coverage
        id: get_coverage
        run: |
          COVERAGE=$(node -p "require('./coverage/coverage-summary.json').total.lines.pct")
          echo "percentage=$COVERAGE" >> $GITHUB_OUTPUT

      - name: Create Job Summary
        run: |
          echo "## Test Coverage: ${{ steps.get_coverage.outputs.percentage }}%" >> $GITHUB_STEP_SUMMARY

      - name: Rename Workflow Run
        run: |
          echo "GITHUB_WORKFLOW_NAME=Test Coverage (${{ steps.get_coverage.outputs.percentage }}%)" >> $GITHUB_ENV
