name: 'coverage'
on:
  pull_request:
    branches:
      - master
      - main

permissions:
  checks: write
  contents: read
  pull-requests: write

# jobs:
#   coverage:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           node-version: '18'
#       - name: Install dependencies
#         run: npm ci
#       - name: Run tests with coverage
#         run: npm test -- --coverage --watchAll=false --ci
#       - name: Report Coverage
#         uses: romeovs/lcov-reporter-action@v0.3.1
#         with:
#           lcov-file: ./coverage/lcov.info
#           github-token: ${{ secrets.GITHUB_TOKEN }}
#           delete-old-comments: true

jobs:
  coverage_report:
    name: Generate coverage report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # ... Generate LCOV files or download it from a different job
      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1
      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v3
        with:
          coverage-files: coverage/lcov.info
          minimum-coverage: 80
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: .
          update-comment: true
