name: 'coverage'
on:
  pull_request:
    branches:
      - master
      - main

permissions:
  checks: write
  contents: read
  pull-requests: write

# jobs:
#   coverage:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           node-version: '18'
#       - name: Install dependencies
#         run: npm ci
#       - name: Run tests with coverage
#         run: npm test -- --coverage --watchAll=false --ci
#       - name: Report Coverage
#         uses: romeovs/lcov-reporter-action@v0.3.1
#         with:
#           lcov-file: ./coverage/lcov.info
#           github-token: ${{ secrets.GITHUB_TOKEN }}
#           delete-old-comments: true

jobs:
  coverage_report:
    name: Generate coverage report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run tests with coverage
        run: npm test -- --coverage --watchAll=false --ci
        continue-on-error: true
      - name: Report Coverage
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          lcov-file: ./coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
          delete-old-comments: true
